[tool.poetry]
name = "mesads"
version = "0.1.0"
description = ""
authors = ["Julien Castets"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^3.2.9"
django-registration = "^3.2"
pip = "^21.3.1"
install = "^1.3.5"
django-autocomplete-light = "^3.8.2"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3.2.2"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
