# Generated by Django 5.2.10 on 2026-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_date', models.DateField(verbose_name="Date d'envoi")),
                ('newsletter', models.FileField(upload_to='newsletters/', verbose_name='Newsletter (format PDF)')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
