# Generated by Django 3.2.9 on 2021-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('insee', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
    ]
