# Generated by Django 3.2.9 on 2021-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('libelle', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siren', models.CharField(max_length=64, unique=True)),
                ('departement', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'EPCI',
                'verbose_name_plural': 'EPCI',
                'unique_together': {('departement', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=16, unique=True)),
                ('departement', models.CharField(max_length=16)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('departement', 'libelle')},
            },
        ),
    ]
