# Generated by Django 3.2.9 on 2021-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fradm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('numero', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
    ]
