# Generated by Django 5.0.6 on 2024-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fradm", "0002_create_extension_unaccent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commune",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="commune",
            name="type_commune",
            field=models.CharField(
                choices=[
                    ("COM", "Commune"),
                    ("COMA", "Commune associée"),
                    ("COMD", "Commune déléguée"),
                    ("ARM", "Arrondissement municipal"),
                ],
                default="COM",
                max_length=16,
                verbose_name="Type de commune",
            ),
            preserve_default=False,
        ),
    ]
