# Generated by Django 3.2.9 on 2021-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fradm', '0002_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCI',
            fields=[
                ('siren', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
