# Generated by Django 5.0.6 on 2024-07-05 11:29

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fradm", "0004_alter_commune_insee_alter_commune_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commune",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="commune",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                fields=("type_commune", "insee"),
                name="fradm_commune_type_commune_insee",
            ),
        ),
    ]
