# Generated by Django 5.0.6 on 2025-12-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fradm", "0005_alter_commune_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commune",
            options={"default_manager_name": "objects"},
        ),
    ]
