# Generated by Django 5.0.6 on 2025-11-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fradm", "0005_alter_commune_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aeroport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("departement", models.CharField(max_length=16)),
            ],
            options={
                "verbose_name": "Aéroport",
                "verbose_name_plural": "Aéroports",
            },
        ),
    ]
