# Generated by Django 5.0.6 on 2026-01-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fradm', '0006_aeroport'),
        ('fradm', '0006_alter_commune_options'),
    ]

    operations = [
    ]
