# Generated by Django 4.1.9 on 2023-10-20 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fradm", "0002_create_extension_unaccent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proprietaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "nom",
                    models.CharField(help_text="Nom du propriétaire", max_length=256),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, help_text="SIRET du propriétaire", max_length=64
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=256)),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Numéro unique identifiant le véhicule relais",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "immatriculation",
                    models.CharField(
                        blank=True,
                        help_text="Plaque d'immatriculation du véhicule",
                        max_length=32,
                    ),
                ),
                (
                    "modele",
                    models.CharField(
                        blank=True,
                        help_text="Marque, modèle et série du véhicule",
                        max_length=256,
                    ),
                ),
                (
                    "motorisation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("essence", "Essence"),
                            ("diesel", "Diesel"),
                            ("hybride", "Hybride"),
                            ("hybride_rechargeable", "Hybride rechargeable"),
                            ("electrique", "Electrique"),
                            ("GPL", "GPL"),
                            ("E85", "E85"),
                        ],
                        help_text="Motorisation du véhicule",
                        max_length=64,
                    ),
                ),
                (
                    "date_mise_circulation",
                    models.DateField(
                        blank=True,
                        help_text="Date de mise en circulation du véhicule",
                        null=True,
                    ),
                ),
                (
                    "nombre_places",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre de places assises (mention S1 sur la carte grise)",
                        null=True,
                    ),
                ),
                (
                    "pmr",
                    models.BooleanField(
                        blank=True,
                        help_text="Le véhicule est-il accessible aux personnes à mobilité réduite ?",
                        null=True,
                    ),
                ),
                (
                    "localisation",
                    models.TextField(
                        blank=True,
                        help_text="Adresse complète de localisation du véhicule",
                    ),
                ),
                (
                    "commune_localisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Commune où est situé le véhicule",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fradm.commune",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fradm.prefecture",
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        help_text="Propriétaire du véhicule",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehicules_relais.proprietaire",
                    ),
                ),
            ],
        ),
    ]
