# Generated by Django 4.1.9 on 2023-11-10 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fradm", "0002_create_extension_unaccent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proprietaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "nom",
                    models.CharField(
                        max_length=256, verbose_name="Nom du propriétaire"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SIRET du propriétaire"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=256, verbose_name="Adresse email"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        unique=True,
                        verbose_name="Numéro unique identifiant le véhicule relais",
                    ),
                ),
                (
                    "immatriculation",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="Plaque d'immatriculation du véhicule",
                    ),
                ),
                (
                    "modele",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        verbose_name="Marque, modèle et série du véhicule",
                    ),
                ),
                (
                    "motorisation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("essence", "Essence"),
                            ("diesel", "Diesel"),
                            ("hybride", "Hybride"),
                            ("hybride_rechargeable", "Hybride rechargeable"),
                            ("electrique", "Electrique"),
                            ("GPL", "GPL"),
                            ("E85", "E85"),
                        ],
                        max_length=64,
                        verbose_name="Motorisation du véhicule",
                    ),
                ),
                (
                    "date_mise_circulation",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de mise en circulation du véhicule",
                    ),
                ),
                (
                    "nombre_places",
                    models.IntegerField(
                        blank=True,
                        help_text="Mention S1 sur la carte grise",
                        null=True,
                        verbose_name="Nombre de places assises",
                    ),
                ),
                (
                    "pmr",
                    models.BooleanField(
                        blank=True,
                        help_text="Cochez la case si je véhicule est accessible. Vous pouvez retrouver cette information sur la mention « J.3 : handicap » de la carte grise du véhicule concerné par l'ADS.",
                        null=True,
                        verbose_name="Le véhicule est accessible aux personnes à mobilité réduite ?",
                    ),
                ),
                (
                    "localisation",
                    models.TextField(
                        blank=True,
                        verbose_name="Adresse complète de localisation du véhicule",
                    ),
                ),
                (
                    "commune_localisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fradm.commune",
                        verbose_name="Commune où est situé le véhicule",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fradm.prefecture",
                        verbose_name="Département du véhicule relais",
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        help_text="Propriétaire du véhicule",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehicules_relais.proprietaire",
                    ),
                ),
            ],
        ),
    ]
