# Generated by Django 4.1.9 on 2023-12-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fradm", "0002_create_extension_unaccent"),
        ("vehicules_relais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="departement",
            field=models.ForeignKey(
                help_text="Un véhicule relais ne peut être enregistré que pour un seul département.",
                on_delete=django.db.models.deletion.RESTRICT,
                to="fradm.prefecture",
                verbose_name="Département du véhicule relais",
            ),
        ),
    ]
