# Generated by Django 4.1.9 on 2023-12-14 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicules_relais", "0002_alter_vehicule_departement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicule",
            name="localisation",
        ),
    ]
