# Generated by Django 4.1.9 on 2024-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicules_relais", "0003_remove_vehicule_localisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="immatriculation",
            field=models.CharField(
                blank=True,
                help_text="La plaque d'immatriculation du véhicule ne peut pas être modifiée une fois le véhicule enregistré.",
                max_length=32,
                verbose_name="Plaque d'immatriculation du véhicule",
            ),
        ),
    ]
