# Generated by Django 4.1.9 on 2024-05-02 10:34

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import mesads.app.models


class Migration(migrations.Migration):
    dependencies = [
        ("fradm", "0002_create_extension_unaccent"),
        ("vehicules_relais", "0004_alter_vehicule_immatriculation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispositionSpecifique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    markdownx.models.MarkdownxField(
                        blank=True,
                        help_text="Format Markdown autorisé",
                        verbose_name="Message à afficher sur le formulaire de création de véhicule",
                    ),
                ),
                (
                    "departement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fradm.prefecture",
                        verbose_name="Département concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposition spécifique",
                "verbose_name_plural": "Dispositions spécifiques",
            },
            bases=(mesads.app.models.CharFieldsStripperMixin, models.Model),
        ),
    ]
