# Generated by Django 5.0.6 on 2025-02-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fradm", "0005_alter_commune_unique_together_and_more"),
        ("vehicules_relais", "0006_alter_vehicule_motorisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="departement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="fradm.prefecture",
                verbose_name="Département du véhicule relais",
            ),
        ),
    ]
