# Generated by Django 5.0.6 on 2025-12-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fradm", "0005_alter_commune_unique_together_and_more"),
        ("vehicules_relais", "0007_alter_vehicule_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="departement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="fradm.prefecture",
                verbose_name="Département du taxis relais",
            ),
        ),
        migrations.AlterField(
            model_name="vehicule",
            name="numero",
            field=models.CharField(
                blank=True,
                max_length=16,
                unique=True,
                verbose_name="Numéro unique identifiant le taxis relais",
            ),
        ),
    ]
