# Generated by Django 4.1.7 on 2023-05-04 20:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_unique_ci_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_ci_email",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_ci_email",
                violation_error_message="Un utilisateur avec cet email existe déjà.",
            ),
        ),
    ]
