# Generated by Django 4.1.7 on 2023-05-04 22:26

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_unique_ci_email_user_unique_ci_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CITextField(error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, unique=True, verbose_name='email address'),
        ),
    ]
