# Generated by Django 4.1.7 on 2023-05-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_ci_email',
        ),
    ]
