# Generated by Django 5.0.6 on 2025-03-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userauditentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userauditentry",
            options={
                "verbose_name": "Historique des connexions",
                "verbose_name_plural": "Historiques des connexions",
            },
        ),
    ]
