# Generated by Django 5.0.6 on 2025-04-25 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_otp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauditentry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
