# Generated by Django 5.0.6 on 2025-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_userauditentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="proconnect_chorusdt",
            field=models.CharField(
                blank=True,
                default="",
                verbose_name="Entité ministérielle / Matricule Agent",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="proconnect_idp_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Identifiant du FI"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="proconnect_siret",
            field=models.CharField(blank=True, default="", verbose_name="SIRET"),
        ),
        migrations.AddField(
            model_name="user",
            name="proconnect_sub",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Identifiant unique proconnect"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="proconnect_uid",
            field=models.CharField(
                blank=True, default="", verbose_name="ID chez le FI"
            ),
        ),
    ]
