# Generated by Django 5.0.6 on 2025-10-28 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_proconnect_chorusdt_user_proconnect_idp_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dernier_affichage",
                    models.DateField(
                        null=True,
                        verbose_name="Date du dernier affichage du composant de notation",
                    ),
                ),
                (
                    "derniere_note",
                    models.DateField(
                        null=True, verbose_name="Date de la dernière notation"
                    ),
                ),
                (
                    "note_facilite",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(5),
                        ],
                        verbose_name="Note de facilité d'usage (sur 5)",
                    ),
                ),
                (
                    "note_qualite",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(5),
                        ],
                        verbose_name="Note de qualité de service (sur 5)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Note de l'utilisateur",
                "verbose_name_plural": "Notes des utilisateurs",
            },
        ),
    ]
