# Generated by Django 5.2.10 on 2026-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_noteutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_collation='case_insensitive', error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
