# Generated by Django 3.2.9 on 2022-01-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="attribution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Gratuitement (délivrée par l'autorité compétente)"),
                    ("paid", "Cession à titre onéreux"),
                    ("other", "Autre"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ADSManagerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ads_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.adsmanager"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
