# Generated by Django 3.2.9 on 2021-11-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fradm', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmanager',
            name='entity_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'fradm'), ('model', 'commune')), models.Q(('app_label', 'fradm'), ('model', 'epci')), models.Q(('app_label', 'fradm'), ('model', 'prefecture')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='adsmanageradministrator',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fradm.prefecture', unique=True),
        ),
    ]
