# Generated by Django 3.2.9 on 2021-11-15 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name': 'Autorité', 'verbose_name_plural': 'Autorités'},
        ),
        migrations.CreateModel(
            name='AuthoritiesUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
