# Generated by Django 3.2.9 on 2021-11-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fradm', '0001_initial'),
        ('app', '0002_auto_20211123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmanageradministrator',
            name='prefecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fradm.prefecture'),
        ),
    ]
