# Generated by Django 3.2.9 on 2021-11-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0003_alter_adsmanageradministrator_prefecture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adsmanager',
            unique_together={('entity_type', 'entity_id')},
        ),
    ]
