# Generated by Django 3.2.9 on 2022-01-31 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_auto_20220127_1440"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adsmanager",
            name="users",
        ),
    ]
