# Generated by Django 3.2.9 on 2022-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_auto_20220425_1813"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.UniqueConstraint(
                fields=("number", "ads_manager_id"), name="unique_ads_number"
            ),
        ),
    ]
