# Generated by Django 4.0.5 on 2022-07-05 15:22

from django.db import migrations, models
import django.db.models.deletion
import mesads.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ads_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[
                    ('titulaire_exploitant', 'Titulaire exploitant'),
                    ('cooperateur', 'Locataire coopérateur'),
                    ('locataire_gerant', 'Locataire gérant'),
                    ('salarie', 'Salarié'),
                    ('autre', 'Autre')
                ], max_length=255)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('siret', models.CharField(blank=True, max_length=128, validators=[mesads.app.models.validate_siret])),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ads')),
            ],
        ),
    ]
