# Generated by Django 4.0.5 on 2022-07-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_ads_user_name_remove_ads_user_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='owner_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
