# Generated by Django 4.0.5 on 2022-07-26 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_combine_owner_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="owner_firstname",
        ),
        migrations.RemoveField(
            model_name="ads",
            name="owner_lastname",
        ),
    ]
