# Generated by Django 4.0.5 on 2022-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_ads_owner_firstname_remove_ads_owner_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='owner_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ads',
            name='owner_mobile',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ads',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
