# Generated by Django 4.0.5 on 2022-09-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_ads_owner_email_ads_owner_mobile_ads_owner_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmanager",
            name="administrator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="app.adsmanageradministrator",
            ),
        ),
    ]
