# Generated by Django 4.0.5 on 2022-09-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_fill_adsmanager_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsmanageradministrator',
            name='ads_managers',
        ),
    ]
