# Generated by Django 4.0.5 on 2022-10-25 09:56

from django.db import migrations, models
import django.db.models.deletion
import mesads.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_adsupdatefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADSLegalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mesads.app.models.get_legal_filename)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ads')),
            ],
        ),
    ]
