# Generated by Django 4.0.5 on 2022-10-25 09:56

from django.db import migrations
from django.db.models import Count


def migrate_legal_file(apps, schema_editor):
    ADS = apps.get_model("app", "ADS")
    ADSLegalFile = apps.get_model("app", "ADSLegalFile")

    for ads in ADS.objects.exclude(legal_file=""):
        ADSLegalFile.objects.create(ads=ads, file=ads.legal_file)


def revert_migrate_legal_file(apps, schema_editor):
    ADSLegalFile = apps.get_model("app", "ADSLegalFile")

    if (
        ADSLegalFile.objects.annotate(count=Count("ads")).filter(count__gt=1).count()
        > 0
    ):
        raise ValueError(
            "Unable to perform backward migration: at least one ADS has more than one legal file"
        )

    for legal_file in ADSLegalFile.objects.all():
        legal_file.ads.legal_file = legal_file.file
        legal_file.ads.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_adslegalfile"),
    ]

    operations = [
        migrations.RunPython(migrate_legal_file, revert_migrate_legal_file),
    ]
