# Generated by Django 4.0.5 on 2022-10-25 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_migrate_to_adslegalfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="legal_file",
        ),
    ]
