# Generated by Django 4.0.5 on 2022-10-25 14:11

from django.db import migrations, models


def copy_ads_creation_date(apps, schema_editor):
    ADSLegalFile = apps.get_model("app", "ADSLegalFile")

    for ads_legal_file in ADSLegalFile.objects.all():
        ads_legal_file.creation_date = ads_legal_file.ads.creation_date
        ads_legal_file.save()


def do_nothing(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_adslegalfile_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adslegalfile",
            name="creation_date",
            field=models.DateField(),
        ),
        migrations.RunPython(copy_ads_creation_date, do_nothing),
    ]
