# Generated by Django 4.0.5 on 2022-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_ads_epci_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
