# Generated by Django 4.0.5 on 2022-12-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_adsuser_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsuser",
            name="license_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
