# Generated by Django 4.0.5 on 2022-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_alter_adsuser_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="owner_siret",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="adsuser",
            name="siret",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
