# Generated by Django 4.0.5 on 2022-12-20 16:23

from django.db import migrations, models
import mesads.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_ads_owner_siret_alter_adsuser_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslegalfile',
            name='file',
            field=models.FileField(max_length=512, upload_to=mesads.app.models.get_legal_filename),
        ),
    ]
