# Generated by Django 4.0.5 on 2022-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_adslegalfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsmanager',
            name='no_ads_declared',
            field=models.BooleanField(default=False, help_text='Cocher cette case si le gestionnaire ne gère aucune ADS.'),
        ),
    ]
