# Generated by Django 4.0.5 on 2023-01-02 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_adsmanager_no_ads_declared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="ads_type",
        ),
    ]
