# Generated by Django 4.1.6 on 2023-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0042_adsmanagerdecree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="transaction_identifier",
            field=models.CharField(
                blank=True,
                help_text="Ne renseignez ce numéro que dans le cas où, au sein de votre commune, vous tenez un registre relatif à l'ensemble des transactions officielles. Si vous ne tenez pas un tel registre, il n'est pas nécessaire de renseigner ce champ.",
                max_length=64,
                verbose_name="Numéro d'identification lié au registre des transactions",
            ),
        ),
    ]
