# Generated by Django 4.1.6 on 2023-03-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_ads_owner_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adslegalfile',
            options={'verbose_name': "Arrêté portant sur l'attribution de l'ADS", 'verbose_name_plural': "Arrêtés portant sur l'attribution de l'ADS"},
        ),
        migrations.AlterModelOptions(
            name='adsmanagerrequest',
            options={'verbose_name': 'Demande pour devenir gestionnaire ADS', 'verbose_name_plural': 'Demandes pour devenir gestionnaire ADS'},
        ),
        migrations.AlterModelOptions(
            name='adsupdatefile',
            options={'verbose_name': "Fichier de mise à jour d'ADS", 'verbose_name_plural': "Fichiers de mise à jour d'ADS"},
        ),
    ]
