# Generated by Django 4.1.7 on 2023-03-30 14:01

from datetime import date

from django.db import migrations
from django.db.models import Q


def fix_data_from_hidden_forms(apps, schema_editor):
    ADS = apps.get_model('app', 'ADS')

    # New ADS or ADS with unknown creation date: remove attribution_type
    for ads in ADS.objects.exclude(
        attribution_type=''
    ).filter(
        Q(ads_creation_date__isnull=False, ads_creation_date__gte=date(2014, 10, 1))
        | Q(ads_creation_date__isnull=True)
    ):
        ads.attribution_type = ''
        ads.save()

    # New ADS or ADS with unknown creation date: remove attribution_reason
    for ads in ADS.objects.exclude(
        attribution_reason=''
    ).filter(
        Q(ads_creation_date__isnull=False, ads_creation_date__gte=date(2014, 10, 1))
        | Q(ads_creation_date__isnull=True)
    ):
        ads.attribution_reason = ''
        ads.save()

    # transaction_identifier can only be set if attribution_type is "paid"
    for ads in ADS.objects.exclude(attribution_type='paid').exclude(transaction_identifier=''):
        ads.transaction_identifier = ''
        ads.save()

    # New ADS or ADS with unknown creation date: remove attribution_reason
    for ads in ADS.objects.filter(
        ads_creation_date__isnull=False, ads_creation_date__gte=date(2014, 10, 1)
    ).exclude(attribution_reason=''):
        ads.attribution_reason = ''
        ads.save()

    # Old ADS: remove owner_license_number if used_by_owner is not true
    for ads in ADS.objects.exclude(owner_license_number='').exclude(
        ads_creation_date__isnull=False, ads_creation_date__gte=date(2014, 10, 1)
    ).exclude(
        used_by_owner__isnull=False, used_by_owner=True
    ):
        ads.owner_license_number = ''
        ads.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_ads_user_for_unknown_ads_creation_date'),
    ]

    operations = [
        migrations.RunPython(fix_data_from_hidden_forms, lambda *args, **kwargs: None),
    ]
