# Generated by Django 4.1.7 on 2023-03-30 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0055_remove_hidden_data"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ads_creation_date__gte", datetime.date(2014, 10, 1)),
                        ("ads_creation_date__isnull", False),
                        ("attribution_type", ""),
                    ),
                    models.Q(
                        ("ads_creation_date__isnull", False),
                        ("ads_creation_date__lt", datetime.date(2014, 10, 1)),
                    ),
                    models.Q(
                        ("ads_creation_date__isnull", True), ("attribution_type", "")
                    ),
                    _connector="OR",
                ),
                name="attribution_type_empty_for_new_ads",
                violation_error_message="Le champ 'Type d'attribution de l'ADS' ne peut être renseigné que pour les ADS créées avant le 1er octobre 2014.",
            ),
        ),
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("attribution_type", "paid"),
                    models.Q(
                        models.Q(("attribution_type", "paid"), _negated=True),
                        ("transaction_identifier", ""),
                    ),
                    _connector="OR",
                ),
                name="transaction_identifier_empty_for_non_paid_ads",
                violation_error_message="Le champ 'Numéro d'identification lié au registre des transactions' ne peut être renseigné que pour les ADS dont le type d'attribution est 'Cession à titre onéreux'.",
            ),
        ),
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ads_creation_date__gte", datetime.date(2014, 10, 1)),
                        ("ads_creation_date__isnull", False),
                        ("attribution_reason", ""),
                    ),
                    models.Q(
                        ("ads_creation_date__isnull", False),
                        ("ads_creation_date__lt", datetime.date(2014, 10, 1)),
                    ),
                    models.Q(
                        ("ads_creation_date__isnull", True), ("attribution_reason", "")
                    ),
                    _connector="OR",
                ),
                name="attribution_reason_empty_for_new_ads",
                violation_error_message="Le champ 'Raison d'attribution' ne peut être renseigné que pour les ADS créées avant le 1er octobre 2014.",
            ),
        ),
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ads_creation_date__gte", datetime.date(2014, 10, 1)),
                        ("ads_creation_date__isnull", False),
                    ),
                    models.Q(
                        ("owner_license_number", ""), ("used_by_owner__isnull", True)
                    ),
                    models.Q(
                        ("owner_license_number", ""),
                        ("used_by_owner", False),
                        ("used_by_owner__isnull", False),
                    ),
                    models.Q(("used_by_owner", True), ("used_by_owner__isnull", False)),
                    _connector="OR",
                ),
                name="owner_license_number_empty_if_not_used_by_owner",
                violation_error_message="Le champ 'Numéro de la carte professionnelle du titulaire' doit être vide si l'ADS n'est pas exploitée par son titulaire.",
            ),
        ),
    ]
