# Generated by Django 4.1.7 on 2023-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_ads_attribution_type_empty_for_new_ads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsuser',
            name='status',
            field=models.CharField(blank=True, choices=[('titulaire_exploitant', 'Titulaire exploitant'), ('cooperateur', 'Locataire coopérateur'), ('locataire_gerant', 'Locataire gérant'), ('salarie', 'Salarié'), ('autre', 'Autre')], max_length=255, verbose_name="Modalité d'exploitation de l'ADS"),
        ),
    ]
