# Generated by Django 4.1.9 on 2023-06-01 14:50

from django.db import migrations, models

import mesads.app.models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0059_alter_adsmanagerrequest_last_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adslegalfile",
            name="file",
            field=models.FileField(
                max_length=512,
                upload_to=mesads.app.models.get_legal_filename,
                verbose_name="Fichier",
            ),
        ),
    ]
