# Generated by Django 4.1.9 on 2023-06-01 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0060_alter_adslegalfile_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adsuser",
            options={
                "verbose_name": "Exploitant de l'ADS",
                "verbose_name_plural": "Exploitants de l'ADS",
            },
        ),
    ]
