# Generated by Django 4.1.9 on 2023-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0062_adslegalfile_deleted_at_adsuser_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="number",
            field=models.CharField(
                help_text="Le numéro est librement fixé par chaque autorité compétente en fonction de son organisation interne.",
                max_length=255,
                verbose_name="Numéro de l'ADS",
            ),
        ),
    ]
