# Generated by Django 4.1.9 on 2023-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0063_alter_ads_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="ads_creation_date",
            field=models.DateField(
                blank=True,
                help_text="Indiquer la date à laquelle l’ADS a été attribuée au titulaire pour la première fois.",
                null=True,
                verbose_name="Date de création de l'ADS",
            ),
        ),
    ]
