# Generated by Django 4.1.9 on 2023-06-15 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0064_alter_ads_ads_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="ads_renew_date",
            field=models.DateField(
                blank=True,
                help_text="Les ADS créées depuis le 1er octobre 2014 sont valables 5 ans et doivent être renouvelées.",
                null=True,
                verbose_name="Date du dernier renouvellement de l'ADS",
            ),
        ),
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ads_creation_date__gte", datetime.date(2014, 10, 1)),
                        ("ads_creation_date__isnull", False),
                    ),
                    models.Q(
                        ("ads_creation_date__isnull", False),
                        ("ads_creation_date__lt", datetime.date(2014, 10, 1)),
                        ("ads_renew_date__isnull", True),
                    ),
                    models.Q(
                        ("ads_creation_date__isnull", True),
                        ("ads_renew_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="renew_date_null_for_old_ads",
                violation_error_message="La date de renouvellement ne peut être renseignée que pour les ADS créées après le 1er octobre 2014.",
            ),
        ),
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ads_renew_date__isnull", True),
                    ("ads_renew_date__gte", models.F("ads_creation_date")),
                    _connector="OR",
                ),
                name="renew_date_after_creation_date",
                violation_error_message="La date de renouvellement de l'ADS doit être postérieure à la date de création.",
            ),
        ),
    ]
