# Generated by Django 4.1.9 on 2023-08-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fradm", "0002_create_extension_unaccent"),
        ("app", "0065_ads_ads_renew_date_ads_renew_date_null_for_old_ads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmanager",
            name="epci_delegate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="fradm.epci",
                verbose_name="EPCI qui gère les ADS",
            ),
        ),
    ]
