# Generated by Django 4.1.9 on 2023-08-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fradm", "0002_create_extension_unaccent"),
        ("app", "0066_adsmanager_epci_delegate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmanager",
            name="epci_delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="Si la gestion des ADS de votre administration est déléguée à un EPCI, sélectionnez-le ici.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="fradm.epci",
                verbose_name="EPCI gestionnaire des ADS",
            ),
        ),
        migrations.AlterField(
            model_name="adsmanager",
            name="no_ads_declared",
            field=models.BooleanField(
                default=False,
                help_text="Cochez cette case si le gestionnaire ne gère aucune ADS.",
                verbose_name="L'administration ne gère aucune ADS",
            ),
        ),
    ]
