# Generated by Django 4.1.9 on 2023-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0068_alter_ads_ads_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmanageradministrator",
            name="referent_emails",
            field=models.TextField(
                blank=True,
                help_text="Emails des référents de votre préfecture, à contacter pour les questions relative aux ADS.",
            ),
        ),
    ]
