# Generated by Django 4.1.9 on 2024-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0069_adsmanageradministrator_referent_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="ads_in_use",
            field=models.BooleanField(
                default=True, verbose_name="L'ADS est-elle actuellement exploitée ?"
            ),
            preserve_default=False,
        ),
    ]
