# Generated by Django 4.1.9 on 2024-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0070_ads_ads_in_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="ads_creation_date",
            field=models.DateField(
                blank=True,
                help_text="Indiquer la date à laquelle l'ADS a été attribuée à un titulaire pour la première fois.<br />Pour les « anciennes ADS » <strong>entrez la date de création initiale de l'ADS</strong>, et pas la date éventuelle de cession à un nouveau titulaire.",
                null=True,
                verbose_name="Date de création initiale de l'ADS",
            ),
        ),
    ]
