# Generated by Django 4.1.9 on 2024-03-11 10:43

from django.db import migrations


def upgrade(apps, schema_editor):
    """Fix ADSUser data, see https://trello.com/c/dG9fG0wC"""

    ADS = apps.get_model("app", "ADS")
    ADSUser = apps.get_model("app", "ADSUser")

    for ads in ADS.objects.filter(used_by_owner=True):
        ads_user = ADSUser(
            ads=ads,
            status="titulaire_exploitant",
            license_number=ads.owner_license_number,
            name="",
            siret="",
        )
        ads_user.save()

    for ads in ADS.objects.filter(used_by_owner=False):
        for ads_user in ads.adsuser_set.all():
            if ads_user.status in ("titulaire_exploitant", "autre"):
                ads_user.status = "legal_representative"
                ads_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0073_alter_adsuser_status"),
    ]

    operations = [
        migrations.RunPython(upgrade),
    ]
