# Generated by Django 4.1.9 on 2024-03-11 15:01

from django.db import migrations


def upgrade(apps, schema_editor):
    """Fix ADSUser data, see https://trello.com/c/dG9fG0wC"""
    ADSUser = apps.get_model("app", "ADSUser")

    for ads_user in ADSUser.objects.filter(status="legal_representative").all():
        if ads_user.siret == "":
            continue

        # ADSUser siret and ADS siret are similar, remove the siret from ADSUser
        if ads_user.ads.owner_siret == ads_user.siret:
            ads_user.siret = ""
            ads_user.save()
            continue

        # Values are different. Discard the SIRET from ADSUser, assuming it is wrong
        if ads_user.ads.owner_siret != "":
            ads_user.siret = ""
            ads_user.save()
            continue

        # ADS.owner_siret is empty, let's use the one from ADSUser
        ads_user.ads.owner_siret = ads_user.siret
        ads_user.ads.save()
        ads_user.siret = ""
        ads_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0077_adsuser_name_empty_for_titulaire_exploitant_and_more"),
    ]

    operations = [
        migrations.RunPython(upgrade),
    ]
