# Generated by Django 4.1.9 on 2024-04-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0080_remove_adsuser_siret_empty_for_titulaire_exploitant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Nom du conducteur"
            ),
        ),
        migrations.AlterField(
            model_name="adsuser",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "titulaire_exploitant",
                        "Le titulaire de l'ADS (personne physique)",
                    ),
                    (
                        "legal_representative",
                        "Le représentant légal de la société titulaire de l'ADS (gérant ou président non salarié)",
                    ),
                    ("salarie", "Salarié du titulaire de l'ADS"),
                    ("cooperateur", "Le locataire-coopérateur de l'ADS"),
                    ("locataire_gerant", "Le locataire-gérant de l'ADS"),
                ],
                max_length=255,
                verbose_name="Qui est le conducteur du taxi ?",
            ),
        ),
    ]
