# Generated by Django 5.0.6 on 2024-06-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0083_notification_ads_created_or_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmanager",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="app.adsmanageradministrator",
            ),
        ),
    ]
