# Generated by Django 5.0.6 on 2024-08-01 08:39

from django.db import migrations, models
from django.db.models import Q


def move_data_to_notes(apps, schema_editor):
    ADS = apps.get_model("app", "ADS")

    for ads in ADS.objects.filter(
        ~Q(attribution_type="")
        | ~Q(transaction_identifier="")
        | ~Q(attribution_reason="")
    ):
        notes = []
        if ads.attribution_type != "":
            notes.append(
                {
                    "paid": "* L'ADS a été cédée au titulaire actuel à titre onéreux",
                    "free": "* L'ADS a été délivrée au titulaire actuel par l'autorité compétente",
                    "other": "",
                }[ads.attribution_type]
            )
        if ads.transaction_identifier:
            notes.append(
                f"* Numéro d'identification lié au registre des transactions : {ads.transaction_identifier}"
            )
        if ads.attribution_reason:
            notes.append(
                f"* Raison de l'attribution de l'ADS au titulaire actuel : {ads.attribution_reason}"
            )
        ads.notes = "\n".join(notes)
        ads.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0084_alter_adsmanager_administrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Champ libre pour les informations complémentaires utiles (numéro d'enregistrement dans le registre des transactions, informations importantes concernant la délivrance ou la cession de l'ADS, etc…)",
                verbose_name="Notes sur l'ADS",
            ),
        ),
        migrations.RunPython(move_data_to_notes, do_nothing),
    ]
