# Generated by Django 5.0.6 on 2024-08-01 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0085_ads_notes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ads",
            name="attribution_type_empty_for_new_ads",
        ),
        migrations.RemoveConstraint(
            model_name="ads",
            name="transaction_identifier_empty_for_non_paid_ads",
        ),
        migrations.RemoveConstraint(
            model_name="ads",
            name="attribution_reason_empty_for_new_ads",
        ),
        migrations.RemoveField(
            model_name="ads",
            name="attribution_reason",
        ),
        migrations.RemoveField(
            model_name="ads",
            name="attribution_type",
        ),
        migrations.RemoveField(
            model_name="ads",
            name="transaction_identifier",
        ),
    ]
