# Generated by Django 5.0.6 on 2024-11-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0086_remove_ads_attribution_type_empty_for_new_ads_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ads",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
