# Generated by Django 5.0.6 on 2025-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0087_alter_ads_creation_date_alter_ads_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsuser",
            name="date_location_gerance",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date du contrat de location-gérance",
            ),
        ),
        migrations.AddConstraint(
            model_name="adsuser",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_location_gerance__isnull", True),
                    models.Q(
                        ("date_location_gerance__isnull", False),
                        ("status", "locataire_gerant"),
                    ),
                    _connector="OR",
                ),
                name="ads_location_gerance_set_only_for_locataire_gerant",
                violation_error_message="La date du contrat de location-gérance ne peut être renseignée que pour un locataire-gérant.",
            ),
        ),
    ]
