# Generated by Django 5.0.6 on 2025-02-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0088_adsuser_date_location_gerance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="attribution_date",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle le titulaire (propriétaire) actuel a racheté l'ADS. Laissez ce champ vide si le titulaire n'a pas changé depuis la création de l'ADS.",
                null=True,
                verbose_name="Date d'attribution de l'ADS au titulaire actuel",
            ),
        ),
    ]
