# Generated by Django 5.0.6 on 2025-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_alter_ads_attribution_date"),
        ("fradm", "0005_alter_commune_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ads",
            name="unique_ads_number",
        ),
        migrations.AddField(
            model_name="ads",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Date de suppression de l'objet. Si cette date est renseignée, l'objet est considéré comme supprimé.",
                null=True,
                verbose_name="Date de suppression",
            ),
        ),
        migrations.AddConstraint(
            model_name="ads",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("number", "ads_manager_id"),
                name="unique_ads_number",
            ),
        ),
    ]
