# Generated by Django 5.0.6 on 2025-04-19 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0092_alter_adsupdatefile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ADSUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Date de suppression de l'objet. Si cette date est renseignée, l'objet est considéré comme supprimé.",
                        null=True,
                        verbose_name="Date de suppression",
                    ),
                ),
                (
                    "serialized",
                    models.TextField(
                        blank=True,
                        verbose_name="Données relatives à l'ADS lors de la mise à jour",
                    ),
                ),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False, verbose_name="Complétude des informations"
                    ),
                ),
                (
                    "debug_missing_fields",
                    models.TextField(
                        blank=True, verbose_name="Message d'erreur de complétude"
                    ),
                ),
                (
                    "ads",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads_update_logs",
                        to="app.ads",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur ayant effectué la mise à jour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise à jour ADS",
                "verbose_name_plural": "Mises à jour ADS",
            },
        ),
    ]
