# Generated by Django 5.0.6 on 2025-05-29 06:10

import django.db.models.deletion
import mesads.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_adsupdatelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Date de suppression de l'objet. Si cette date est renseignée, l'objet est considéré comme supprimé.",
                        null=True,
                        verbose_name="Date de suppression",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Demande valide"),
                            ("incomplete", "Demande incomplète"),
                        ],
                        max_length=64,
                        verbose_name="Statut de l'entrée de la liste d'attente",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Cette date est mise à jour automatiquement à chaque fois que l'entrée de la liste d'attente est modifiée.",
                        verbose_name="Date de la dernière mise à jour de l'entrée de la liste d'attente",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Laisser ce champ vide pour générer un nouveau numéro d'enregistrement",
                        max_length=64,
                        verbose_name="N° d'enregistrement",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Attention : la liste d'attente est réservée uniquement aux personnes physiques. Les personnes morales, telles que les sociétés, ne peuvent y être inscrites.",
                        max_length=1024,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Il vous appartient de vérifier que le demandeur dispose d'une carte professionnelle en cours de validité au moment de l'inscription ou du renouvellement de la demande",
                        max_length=64,
                        verbose_name="N° de la carte professionnelle",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=128, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="Adresse postale"
                    ),
                ),
                (
                    "initial_request_date",
                    models.DateField(
                        verbose_name="Date de dépôt de la demande initiale"
                    ),
                ),
                (
                    "last_renew_date",
                    models.DateField(
                        verbose_name="Date de la dernière demande de renouvellement"
                    ),
                ),
                (
                    "end_validity_date",
                    models.DateField(
                        verbose_name="Date de fin de validité de la demande"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Champ libre pour les informations complémentaires utiles (date de la dernière relance, …)",
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "used_ads_two_years",
                    models.BooleanField(
                        blank=True,
                        help_text="Sont prioritaires pour une nouvelle ADS les conducteurs ayant exploité une ADS au moins deux ans au cours des cinq dernières années ; les demandes valides des autres ne sont attribuées qu'en l'absence de demandes prioritaires.",
                        null=True,
                        verbose_name="Sur les 5 dernières années, le conducteur a-t'il exploité une ADS pendant au moins 2 ans ?",
                    ),
                ),
                (
                    "ads_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.adsmanager",
                        verbose_name="Gestionnaire ADS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste d'attente",
                "verbose_name_plural": "Listes d'attente",
            },
            bases=(mesads.app.models.CharFieldsStripperMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="waitinglist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("number", "ads_manager_id"),
                name="unique_waiting_list_number",
                violation_error_message="Une entrée dans la liste d'attente avec ce numéro existe déjà.",
            ),
        ),
    ]
