# Generated by Django 5.0.6 on 2025-10-07 15:12

import django.db.models.deletion
import mesads.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_adsupdatelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionListeAttente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Date de suppression de l'objet. Si cette date est renseignée, l'objet est considéré comme supprimé.",
                        null=True,
                        verbose_name="Date de suppression",
                    ),
                ),
                (
                    "derniere_maj",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Cette date est mise à jour automatiquement à chaque fois que l'entrée de la liste d'attente est modifiée.",
                        verbose_name="Date de la dernière mise à jour de l'entrée de la liste d'attente",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Vous êtes libre de fixer le numéro de votre choix. Vous pouvez choisir de le générer automatiquement.",
                        max_length=64,
                        verbose_name="Numéro d'enregistrement",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Attention :\xa0 seule une personne physique peut être inscrite sur une liste d'attente, à l'exclusion des personnes morales (sociétés)",
                        max_length=1024,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        help_text="Attention :\xa0 seule une personne physique peut être inscrite sur une liste d'attente, à l'exclusion des personnes morales (sociétés)",
                        max_length=1024,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "numero_licence",
                    models.CharField(
                        help_text="Attention :\xa0il vous appartient de vérifier que le demandeur dispose d’une carte professionnelle en cours de validité au moment de l'inscription ou du renouvellement de la demande)\xa0",
                        max_length=64,
                        verbose_name="N° de la carte professionnelle",
                    ),
                ),
                (
                    "numero_telephone",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=128, verbose_name="Email"),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="Adresse postale"
                    ),
                ),
                (
                    "date_depot_inscription",
                    models.DateField(
                        verbose_name="Date de dépôt de la demande initiale"
                    ),
                ),
                (
                    "date_dernier_renouvellement",
                    models.DateField(
                        verbose_name="Date de la dernière demande de renouvellement"
                    ),
                ),
                (
                    "date_fin_validite",
                    models.DateField(
                        help_text="Par défaut, la demande devient invalide si son dépôt initial ou son renouvellement date de plus d’un an.",
                        verbose_name="Date de fin de validité de la demande",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Champ libre pour les informations complémentaires utiles (date de la dernière relance, …)",
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "exploitation_ads",
                    models.BooleanField(
                        help_text="Sont prioritaires pour une nouvelle ADS les conducteurs ayant exploité une ADS au moins deux ans au cours des cinq dernières années ; les demandes valides des autres ne sont attribuées qu'en l'absence de demandes prioritaires.",
                        verbose_name="Sur les 5 dernières années, le conducteur a-t'il exploité une ADS pendant au moins 2 ans ?",
                    ),
                ),
                (
                    "motif_archivage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("absence_reponse", "Absence de réponse du demandeur"),
                            ("informations_erronees", "Informations erronnées"),
                            ("demande_non_renouvellee", "Demande non renouvellée"),
                            (
                                "non_respect_conditions",
                                "Non respect des conditions réglementaires",
                            ),
                            ("demande_candidat", "A la demande du candidat"),
                            ("autre", "Autre"),
                            ("ads_attribuee", "ADS attribuée"),
                        ],
                        max_length=255,
                        verbose_name="Motif d'archivage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inscrit", "Inscrit"),
                            ("attente_reponse", "En attente de réponse du demandeur"),
                            ("reponse_ok", "Réponse positive du demandeur"),
                        ],
                        default="inscrit",
                        max_length=20,
                        verbose_name="Statut de la demande",
                    ),
                ),
                (
                    "date_contact",
                    models.DateField(
                        blank=True,
                        help_text="Date à laquelle vous avez contacté le demandeur",
                        null=True,
                        verbose_name="Date de contact du demandeur",
                    ),
                ),
                (
                    "delai_reponse",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Le délai de réponse que vous accordez au demandeur pour vous répondre (à titre informatif)",
                        null=True,
                        verbose_name="Délai de réponse (en jours)",
                    ),
                ),
                (
                    "ads_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inscriptions_liste_attente",
                        to="app.adsmanager",
                        verbose_name="Gestionnaire ADS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription liste d'attente",
                "verbose_name_plural": "Inscriptions liste d'attente",
            },
            bases=(mesads.app.models.CharFieldsStripperMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="inscriptionlisteattente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("numero", "ads_manager_id"),
                name="unique_waiting_list_number",
                violation_error_message="Une entrée dans la liste d'attente avec ce numéro existe déjà.",
            ),
        ),
    ]
