# Generated by Django 5.0.6 on 2025-05-17 06:50

import django.db.models.deletion
import mesads.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_adsupdatelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Date de suppression de l'objet. Si cette date est renseignée, l'objet est considéré comme supprimé.",
                        null=True,
                        verbose_name="Date de suppression",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Laisser ce champ vide pour générer un nouveau numéro d'enregistrement",
                        max_length=64,
                        verbose_name="N° d'enregistrement",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Attention : seule une personne physique peut être inscrite sur une liste d'attente",
                        max_length=1024,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Il vous appartient de vérifier que le demandeur dispose d'une carte professionnelle en cours de validité au moment de l'inscription ou du renouvellement de la demande",
                        max_length=64,
                        verbose_name="N° de la carte professionnelle",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=128, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="Adresse postale"
                    ),
                ),
                (
                    "initial_request_date",
                    models.DateField(
                        verbose_name="Date de dépôt de la demande initiale"
                    ),
                ),
                (
                    "last_update_date",
                    models.DateField(
                        verbose_name="Date de la dernière demande de renouvellement"
                    ),
                ),
                (
                    "end_validity_date",
                    models.DateField(
                        verbose_name="Date de fin de validité de la demande"
                    ),
                ),
                (
                    "ads_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.adsmanager",
                        verbose_name="Gestionnaire ADS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste d'attente",
                "verbose_name_plural": "Listes d'attente",
            },
            bases=(mesads.app.models.CharFieldsStripperMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="waitinglist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("number", "ads_manager_id"),
                name="unique_waiting_list_number",
                violation_error_message="Une entrée dans la liste d'attente avec ce numéro existe déjà.",
            ),
        ),
    ]
