# Generated by Django 5.0.6 on 2025-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_waitinglist_waitinglist_unique_waiting_list_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglist",
            name="name",
            field=models.CharField(
                help_text="Attention : la liste d'attente est réservée uniquement aux personnes physiques. Les personnes morales, telles que les sociétés, ne peuvent y être inscrites.",
                max_length=1024,
                verbose_name="Nom",
            ),
        ),
    ]
