# Generated by Django 5.0.6 on 2025-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0094_inscriptionlisteattente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="motif_archivage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("absence_reponse", "Absence de réponse du demandeur"),
                    ("informations_erronees", "Informations erronnées"),
                    ("demande_non_renouvellee", "Demande non renouvelée"),
                    (
                        "non_respect_conditions",
                        "Non respect des conditions réglementaires",
                    ),
                    ("demande_candidat", "A la demande du candidat"),
                    ("autre", "Autre"),
                    ("ads_attribuee", "ADS attribuée"),
                ],
                max_length=255,
                verbose_name="Motif d'archivage",
            ),
        ),
    ]
