# Generated by Django 5.0.6 on 2025-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_inscriptionlisteattente_motif_archivage"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionlisteattente",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inscrit", "Inscrit"),
                    ("attente_reponse", "En attente de réponse du demandeur"),
                    ("reponse_ok", "Réponse positive du demandeur"),
                ],
                default="inscrit",
                max_length=20,
                verbose_name="Statut de la demande",
            ),
        ),
    ]
