# Generated by Django 5.0.6 on 2025-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0095_alter_inscriptionlisteattente_motif_archivage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="date_dernier_renouvellement",
            field=models.DateField(
                blank=True, verbose_name="Date de la dernière demande de renouvellement"
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="date_fin_validite",
            field=models.DateField(
                blank=True,
                help_text="Par défaut, la demande devient invalide si son dépôt initial ou son renouvellement date de plus d’un an.",
                verbose_name="Date de fin de validité de la demande",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Vous êtes libre de fixer le numéro de votre choix. SI vous ne remplissez pas ce champ, un numéro sera généré automatiquement.",
                max_length=64,
                verbose_name="Numéro d'enregistrement",
            ),
        ),
    ]
