# Generated by Django 5.0.6 on 2025-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_inscriptionlisteattente_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionlisteattente",
            name="date_contact",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle vous avez contacté le demandeur",
                null=True,
                verbose_name="Date de contact du demandeur",
            ),
        ),
    ]
