# Generated by Django 5.0.6 on 2025-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0096_alter_inscriptionlisteattente_date_dernier_renouvellement_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="date_dernier_renouvellement",
            field=models.DateField(
                blank=True,
                default=None,
                verbose_name="Date de la dernière demande de renouvellement",
            ),
        ),
    ]
