# Generated by Django 5.0.6 on 2025-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0097_inscriptionlisteattente_date_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionlisteattente",
            name="delai_reponse",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Le délai de réponse que vous accordez au demandeur pour vous répondre (à titre informatif)",
                null=True,
                verbose_name="Délai de réponse (en jours)",
            ),
        ),
    ]
