# Generated by Django 5.0.6 on 2025-10-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0097_alter_inscriptionlisteattente_date_dernier_renouvellement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="date_dernier_renouvellement",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date de la dernière demande de renouvellement",
            ),
        ),
    ]
