# Generated by Django 5.0.6 on 2025-10-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0098_alter_inscriptionlisteattente_date_dernier_renouvellement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="email",
            field=models.EmailField(max_length=128, verbose_name="Email"),
        ),
    ]
