# Generated by Django 5.0.6 on 2025-10-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0099_alter_inscriptionlisteattente_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inscriptionlisteattente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("numero_licence",),
                name="unique_numero_licence",
                violation_error_message="Une entrée dans la liste d'attente avec ce numéro existe déjà.",
            ),
        ),
    ]
