# Generated by Django 5.0.6 on 2025-11-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_inscriptionlisteattente_unique_numero_licence"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inscriptionlisteattente",
            name="unique_numero_licence",
        ),
    ]
