# Generated by Django 5.0.6 on 2025-11-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0103_remove_inscriptionlisteattente_exploitation_ads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmanager",
            name="liste_attente_publique",
            field=models.BooleanField(
                default=False,
                help_text="Cochez cette case pour que la liste d'attente de l'administration soit publique.",
            ),
        ),
    ]
