# Generated by Django 5.0.6 on 2025-11-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0104_adsmanager_liste_attente_publique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="numero_licence",
            field=models.CharField(
                help_text="Attention :\xa0il vous appartient de vérifier que le demandeur dispose d’une carte professionnelle en cours de validité au moment de l'inscription ou du renouvellement de la demande\xa0",
                max_length=64,
                verbose_name="N° de la carte professionnelle",
            ),
        ),
    ]
