# Generated by Django 5.0.6 on 2025-11-18 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0105_alter_inscriptionlisteattente_numero_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionlisteattente",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Cette date est renseigné automatiquement lors de la création de l'inscription.",
                verbose_name="Date de création de l'inscription",
            ),
            preserve_default=False,
        ),
    ]
