# Generated by Django 5.0.6 on 2025-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0106_inscriptionlisteattente_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="eco_vehicle",
            field=models.BooleanField(
                blank=True,
                help_text='Vous pouvez retrouver cette information sur la mention P.3 de la carte grise du véhicule concerné par l\'ADS. L\'ensemble des abréviations est disponible sur legifrance : <a href="https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000044084721" target="_blank">https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000044084721<span class="fr-sr-only"> Nouvelle fenêtre</span></a> ',
                null=True,
                verbose_name="Véhicule électrique ou hybride ?",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="date_depot_inscription",
            field=models.DateField(
                help_text="Format: JJ/MM/AAAA",
                verbose_name="Date de dépôt de la demande initiale",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="date_dernier_renouvellement",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Format: JJ/MM/AAAA",
                null=True,
                verbose_name="Date de la dernière demande de renouvellement",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="email",
            field=models.EmailField(
                help_text="example@test.com",
                max_length=128,
                verbose_name="Adresse électronique",
            ),
        ),
    ]
