# Generated by Django 5.0.6 on 2025-11-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0106_inscriptionlisteattente_date_creation"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmanager",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "fradm"), ("model", "commune")),
                    models.Q(("app_label", "fradm"), ("model", "epci")),
                    models.Q(("app_label", "fradm"), ("model", "prefecture")),
                    models.Q(("app_label", "fradm"), ("model", "aeroport")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
