# Generated by Django 5.0.6 on 2025-12-18 16:28

import mesads.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0107_alter_ads_eco_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmanagerdecree",
            name="file",
            field=models.FileField(upload_to=mesads.app.models.get_decree_filename),
        ),
        migrations.AlterField(
            model_name="adsupdatefile",
            name="update_file",
            field=models.FileField(upload_to=mesads.app.models.get_update_filename),
        ),
        migrations.AlterField(
            model_name="inscriptionlisteattente",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Vous êtes libre de fixer le numéro de votre choix. Si vous ne remplissez pas ce champ, un numéro sera généré automatiquement.",
                max_length=64,
                verbose_name="Numéro d'enregistrement",
            ),
        ),
    ]
