# Generated by Django 5.0.6 on 2026-01-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_alter_adsmanager_content_type'),
        ('app', '0108_alter_adsmanagerdecree_file_and_more'),
    ]

    operations = [
    ]
