# Generated by Django 5.2.10 on 2026-02-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_merge_20260112_1826'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeGestionPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_gestion_prefecture', to='app.adsmanageradministrator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_gestion_prefecture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande pour devenir gestionnaire de préfecture',
                'verbose_name_plural': 'Demandes pour devenir gestionnaire de préfecture',
                'unique_together': {('user', 'administrator')},
            },
        ),
    ]
