# Generated by Django 5.2.10 on 2026-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_demandegestionprefecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandegestionprefecture',
            name='accepted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandegestionprefecture',
            name='statut',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Acceptée'), ('REFUSE', 'Refusée')], default='EN_ATTENTE', verbose_name='Statut de la demande'),
        ),
    ]
