# Generated by Django 5.2.10 on 2026-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_demandegestionprefecture_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsmanagerdecree',
            name='date_arrete',
            field=models.DateField(null=True, verbose_name="Date de prise de l'arrêté"),
        ),
    ]
