# Generated by Django 5.2.10 on 2026-03-04 09:33

from django.db import migrations

def set_default_arrete_date(app, schema_editor):
    ADSManagerDecree = app.get_model('app', "ADSManagerDecree")
    from django.db.models import F
    ADSManagerDecree.objects.all().update(date_arrete=F("creation_date__date"))


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_adsmanagerdecree_date_arrete'),
    ]

    operations = [
        migrations.RunPython(set_default_arrete_date)
    ]
