# Generated by Django 5.2.10 on 2026-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_auto_20260304_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmanagerdecree',
            name='date_arrete',
            field=models.DateField(verbose_name="Date de prise de l'arrêté"),
        ),
    ]
