# Generated by Django 5.2.10 on 2026-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_alter_adsmanagerdecree_date_arrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsmanagerdecree',
            name='nombre_ads',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nombre d'ADS autorisées"),
        ),
    ]
