# Generated by Django 5.2.10 on 2026-04-21 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_adsmanagerdecree_nombre_ads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAccesLectureSeule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Acceptée'), ('REFUSE', 'Refusée')], default='EN_ATTENTE', verbose_name='Statut de la demande')),
                ('accepted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces_lecture_seule', to='app.adsmanageradministrator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces_lecture_seule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande pour un accès en lecture seule',
                'verbose_name_plural': 'Demandes pour accès en lecture seule',
                'unique_together': {('user', 'administrator')},
            },
        ),
    ]
