# Generated by Django 5.2.17 on 2026-09-08 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_rename_registre_transaction_publique_adsmanager_registre_transaction_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeregistretransaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date de création de l'entrée"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entreeregistretransaction',
            name='ancien_exploitant',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ancien exploitant, Nom - Prénom ou Dénomination sociale'),
        ),
        migrations.AlterField(
            model_name='entreeregistretransaction',
            name='nouvel_exploitant',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nouvel exploitant, Nom - Prénom ou Dénomination sociale'),
        ),
    ]
