# Generated by Django 5.2.17 on 2026-09-02 13:36

from django.db import migrations
from datetime import date

def migrate_administrators(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DemandeGestionPrefecture = apps.get_model("app", "DemandeGestionPrefecture")
    ADSManagerAdministrator = apps.get_model("app", "ADSManagerAdministrator")
    ACCEPTE = "ACCEPTE"
    for administrator in ADSManagerAdministrator.objects.all():
        for user in administrator.users.all():
            demande = DemandeGestionPrefecture.objects.filter(user=user).first()
            if demande:
                if demande.statut != ACCEPTE:
                    demande.statut = ACCEPTE
                    demande.accepted_at = date.today()
                    demande.save()
                
            else:
                DemandeGestionPrefecture.objects.create(
                    user=user,
                    administrator=administrator,
                    statut=ACCEPTE,
                    accepted_at=date.today()
                )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_rename_registre_transaction_publique_adsmanager_registre_transaction_public_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_administrators),
    ]
