# Generated by Django 5.2.17 on 2026-09-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_auto_20260902_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsmanageradministrator',
            name='users',
        ),
    ]
