# Generated by Django 5.2.17 on 2026-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_entreeregistretransaction_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandegestionprefecture',
            name='statut_user',
            field=models.CharField(default='', max_length=255, verbose_name='Statut au sein de la préfecture'),
        ),
    ]
